datamatrix-web/src/main/java/de/crazymail/datamatrix/controller/AttributeController.java
package de.crazymail.datamatrix.controller;

import de.crazymail.datamatrix.database.exception.InvalidSequenceException;
import de.crazymail.datamatrix.business.manager.AttributeManager;
import de.crazymail.datamatrix.model.Attribute;
import org.primefaces.event.SelectEvent;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.event.ActionEvent;
import javax.inject.Named;
import javax.security.enterprise.authentication.mechanism.http.CustomFormAuthenticationMechanismDefinition;
import javax.security.enterprise.authentication.mechanism.http.LoginToContinue;
import javax.security.enterprise.identitystore.DatabaseIdentityStoreDefinition;
import java.util.List;

@Named("attributeController")
@SessionScoped
@CustomFormAuthenticationMechanismDefinition(loginToContinue = @LoginToContinue(loginPage = "/login.jsf"))
public class AttributeController extends GenericController {

    @EJB
    private AttributeManager attributeManager;

    public AttributeController() {
        super(AttributeController.class);
    }

    private Attribute attribute;
    private Attribute selectedAttribute;

    public Attribute getSelectedAttribute() {
        return selectedAttribute;
    }

    public void setSelectedAttribute(Attribute selectedAttribute) {
        this.selectedAttribute = selectedAttribute;
    }

    public Attribute getAttribute() {
        log("getAttribute: attribute is null: " + (attribute == null));
        return attribute;
    }

    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }

    public void addAttribute(ActionEvent actionEvent) {
        this.attribute = this.attributeManager.create();
        log("addAttribute: attribute is null: " + (attribute == null));
        this.openDialog("addeditdialog");
    }

    public void onSelectAttribute(SelectEvent event) {
        this.update("listform:buttonaddattribute");
        this.update("listform:buttoneditattribute");
        this.update("listform:buttonarchiveattribute");
    }

    public List<Attribute> getAttributes() {
        log("getAttributes");
        return this.attributeManager.getAll();
    }

    public void saveAttribute(ActionEvent actionEvent) throws InvalidSequenceException {
        log("saveAttribute");
        try {
            this.attributeManager.save(this.attribute);
            this.closeDialog("addeditdialog");
            this.update("listform:attributesTable");
            this.attribute = null;
        } catch(Exception ex) {
            log(ex.getMessage());
        }
    }

    public void editAttribute(ActionEvent actionEvent) {
        this.attribute = this.selectedAttribute;
        this.openDialog("addeditdialog");
    }

    public void cancelAddAttribute(ActionEvent actionEvent) {
        this.attribute = null;
        this.closeDialog("addeditdialog");
    }

    public void archiveAttribute(ActionEvent actionEvent) throws InvalidSequenceException {
        this.attribute = this.selectedAttribute;
        this.attribute = this.attributeManager.archive(this.attribute);
        this.update("listform:attributesTable");
    }

    public boolean isArchivable() {
        return !(this.selectedAttribute == null);
    }

    public boolean isEditable() {
        return !(this.selectedAttribute == null);
    }

}

datamatrix-web/src/main/java/de/crazymail/datamatrix/controller/GenericController.java
package de.crazymail.datamatrix.controller;

import org.primefaces.context.RequestContext;

import java.io.Serializable;
import java.util.logging.Logger;

public abstract class GenericController implements Serializable {
    private Logger logger = null;

    public GenericController(Class clazz) {
        this.logger = Logger.getLogger(clazz.toString());
    }

    public void log(String msg) {
        this.logger.info(msg);
    }

    public void openDialog(String dialogId) {
        RequestContext context = RequestContext.getCurrentInstance();
        context.execute("PF('" + dialogId + "').show();");
    }

    public void closeDialog(String dialogId) {
        RequestContext context = RequestContext.getCurrentInstance();
        context.execute("PF('" + dialogId + "').hide();");
    }

    public void update(String updateId) {
        RequestContext.getCurrentInstance().update(updateId);
    }

}

datamatrix-web/src/main/java/de/crazymail/datamatrix/controller/LoginBean.java
package de.crazymail.datamatrix.controller;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.security.enterprise.AuthenticationStatus;
import javax.security.enterprise.SecurityContext;
import javax.security.enterprise.credential.Credential;
import javax.security.enterprise.credential.Password;
import javax.security.enterprise.credential.UsernamePasswordCredential;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import static javax.faces.application.FacesMessage.SEVERITY_ERROR;
import static javax.security.enterprise.AuthenticationStatus.SEND_CONTINUE;
import static javax.security.enterprise.AuthenticationStatus.SEND_FAILURE;
import static javax.security.enterprise.authentication.mechanism.http.AuthenticationParameters.withParams;

@Named
@RequestScoped
public class LoginBean {

    @Inject
    private SecurityContext securityContext;

    @Inject
    private FacesContext facesContext;

    private String username, password;

    public void login() {

        Credential credential = new UsernamePasswordCredential(username, new Password(password));

        AuthenticationStatus status = securityContext.authenticate(
                getRequest(),
                getResponse(),
                withParams()
                        .credential(credential));

        if (status.equals(SEND_CONTINUE)) {
            // Authentication mechanism has send a redirect, should not
            // send anything to response from JSF now.
            facesContext.responseComplete();
        } else if (status.equals(SEND_FAILURE)) {
            addError("Authentication failed");
        }

    }

    private HttpServletResponse getResponse() {
        return (HttpServletResponse) facesContext
                .getExternalContext()
                .getResponse();
    }

    private HttpServletRequest getRequest() {
        return (HttpServletRequest) facesContext
                .getExternalContext()
                .getRequest();
    }

    private void addError(String message) {
        facesContext.addMessage(null, new FacesMessage(SEVERITY_ERROR, message, null));
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}

datamatrix-web/src/main/java/de/crazymail/datamatrix/controller/TypeController.java
package de.crazymail.datamatrix.controller;

import de.crazymail.datamatrix.database.exception.InvalidSequenceException;
import de.crazymail.datamatrix.business.manager.AttributeManager;
import de.crazymail.datamatrix.business.manager.TypeManager;
import de.crazymail.datamatrix.model.Attribute;
import de.crazymail.datamatrix.model.Type;
import de.crazymail.datamatrix.util.converter.TypeToTreeNodeConverter;
import org.primefaces.event.NodeSelectEvent;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;

import javax.enterprise.context.SessionScoped;
import javax.faces.event.ActionEvent;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.ArrayList;
import java.util.List;

@Named("typeController")
@SessionScoped
public class TypeController extends GenericController {

    @Inject
    private TypeManager typeManager;

    @Inject
    private AttributeManager attributeManager;

    private TreeNode selectedTreeNode;

    private Type type;

    private List<Attribute> selectedAttributesToAdd;

    public TypeController() {
        super(TypeController.class);
    }

    public TreeNode getSelectedTreeNode() {
        return selectedTreeNode;
    }

    public void setSelectedTreeNode(TreeNode selectedTreeNode) {
        if(selectedTreeNode != null)
            log("selectedTreeNode: " + ((Type)selectedTreeNode.getData()).getName());
        else
            log("selectedTreeNode: null");

        this.selectedTreeNode = selectedTreeNode;
    }

    public List<Attribute> getSelectedAttributesToAdd() {
        return selectedAttributesToAdd;
    }

    public void setSelectedAttributesToAdd(List<Attribute> selectedAttributesToAdd) {
        this.selectedAttributesToAdd = selectedAttributesToAdd;
    }

    public List<Type> getTypes() {
        return this.typeManager.getAll();
    }

    public void addType(ActionEvent actionEvent) {
        if(this.selectedTreeNode != null)
            this.type = this.typeManager.create((Type)this.selectedTreeNode.getData());
        else
            this.type = this.typeManager.create();
        this.openDialog("addeditdialog");
    }

    public void editType(ActionEvent actionEvent) {
        this.type = (Type)this.selectedTreeNode.getData();
        this.openDialog("addeditdialog");
    }

    public void showAttributes() {
        this.update("attributesTableForm:attributesTable");
        this.openDialog("attributesdialog");
    }

    public void archiveType(ActionEvent actionEvent) throws InvalidSequenceException {
        this.type = (Type) this.selectedTreeNode.getData();
        this.type = this.typeManager.archive(this.type);
        this.update("listform:typestree");
    }

    public void closeAttributeDialog(ActionEvent actionEvent) {
        this.closeDialog("attributesdialog");
    }

    public void saveType(ActionEvent actionEvent) throws InvalidSequenceException {
        try {
            this.typeManager.save(this.type);
            this.closeDialog("addeditdialog");
            this.update("listform:typestree");
            this.type = null;
        } catch(Exception ex) {
            log(ex.getMessage());
        }
    }

    public void cancelAddType(ActionEvent actionEvent) {
        this.type = null;
        this.closeDialog("addeditdialog");
    }

    public Type getType() {
        return type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    public void openAddAttributeDialog(ActionEvent actionEvent) {
        this.update("selectattributesform:attributesTable");
        this.openDialog("addattributedialog");
    }

    public List<Attribute> availableAttributes() {
        return this.attributeManager.getAll();
    }

    public void saveAttributes(ActionEvent actionEvent) throws InvalidSequenceException {
        this.log("count array elements: " + this.selectedAttributesToAdd.size());

        this.type = (Type) this.selectedTreeNode.getData();
        this.type = this.typeManager.addAttributes(this.type, this.selectedAttributesToAdd);
        this.type = this.typeManager.save(this.type);
        
        this.closeDialog("addattributedialog");
        this.update("listform:attributesTable");
       
    }

    public void cancelAddAttributes(ActionEvent actionEvent) {
        this.closeDialog("addattributedialog");
    }

    public void onSelectTypeNode(NodeSelectEvent event) {
        log("update listform:attributesTable");

        this.update("listform:attributesTable");
        this.update("listform:buttonaddtype");
        this.update("listform:buttonedittype");
        this.update("listform:buttonaddattribute");
        this.update("listform:buttonarchivetype");
    }

    public TreeNode getRootNodes() {

        List<Type> lst = this.typeManager.getRootTypes();
        TreeNode dummy = new DefaultTreeNode("some String", null);
        for(Type t : lst) {

            log("count children: " + t.getChildren().size());
            TreeNode tt = TypeToTreeNodeConverter.processTree(t, dummy);
        }



        return dummy;
    }

    public List<Attribute> getAttributesforType() {
        if(this.selectedTreeNode != null) {
            Type t = ((Type) this.selectedTreeNode.getData());
            return this.typeManager.getAttributesEffective(t);
        } else
            return new ArrayList<>();
    }

    public boolean isArchivable() {
        return !(this.selectedTreeNode == null);
    }

    public boolean isEditable() {
        return !(this.selectedTreeNode == null);
    }

    public boolean isAttributeAddable() {
        return !(this.selectedTreeNode == null);
    }
}

datamatrix-web/src/main/webapp/attributes.xhtml
<ui:composition template="template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:define name="content">

        <h:form id="listform">
            <p:dataTable
                    id="attributesTable"
                    var="attr"
                    value="#{attributeController.getAttributes()}"
                    rowKey="#{attr.id}"
                    paginator="true"
                    rows="15"
                    paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                    rowsPerPageTemplate="5,10,15"
                    paginatorPosition="bottom"
                    selectionMode="single"
                    selection="#{attributeController.selectedAttribute}">

                <p:ajax
                        event="rowSelect"
                        update=":listform:buttonaddattribute :listform:buttoneditattribute :listform:buttonarchiveattribute"/>

                <p:column headerText="#{msg['datatable.attribute.id']}">
                    <h:outputText value="#{attr.id}"/>
                </p:column>

                <p:column headerText="#{msg['datatable.attribute.number']}">
                    <h:outputText value="#{attr.number}"/>
                </p:column>

                <p:column headerText="#{msg['datatable.attribute.name']}">
                    <h:outputText value="#{attr.name}"/>
                </p:column>

                <p:column headerText="#{msg['datatable.attribute.description']}">
                    <h:outputText value="#{attr.description}"/>
                </p:column>

                <!--
                <f:facet name="paginatorBottomLeft">

                </f:facet>
                -->

            </p:dataTable>

            <p:commandButton
                    id="buttonaddattribute"
                    value="#{msg['button.add']}"
                    ajax="true"
                    actionListener="#{attributeController.addAttribute}"
                    update=":addeditform"
                    styleClass="ui-priority-primary"/>

            <p:commandButton
                    id="buttoneditattribute"
                    value="#{msg['button.edit']}"
                    ajax="true"
                    actionListener="#{attributeController.editAttribute}"
                    update=":addeditform"
                    disabled="#{not attributeController.isEditable()}"
                    styleClass="ui-priority-primary"/>

            <p:commandButton
                    id="buttonarchiveattribute"
                    value="#{msg['button.archive']}"
                    ajax="true"
                    actionListener="#{attributeController.archiveAttribute}"
                    disabled="#{not attributeController.isArchivable()}"
                    styleClass="ui-priority-primary"/>
        </h:form>

        <p:dialog
                id="addeditdialog"
                modal="true"
                resizable="false"
                draggable="false"
                closable="false"
                header="#{msg['attribute.addedit.dialogtitle']}"
                widgetVar="addeditdialog">

            <h:form id="addeditform">
                <p:panelGrid columns="2">

                    <h:outputText value="#{msg['attribute.form.number']}"/>
                    <h:inputText value="#{attributeController.attribute.number}"/>

                    <h:outputText value="#{msg['attribute.form.name']}"/>
                    <h:inputText value="#{attributeController.attribute.name}"/>

                    <h:outputText value="#{msg['attribute.form.description']}"/>
                    <h:inputText value="#{attributeController.attribute.description}"/>

                    <p:commandButton
                            value="#{msg['button.save']}"
                            ajax="true"
                            actionListener="#{attributeController.saveAttribute}"
                            update=":addeditform"
                            styleClass="ui-priority-primary"/>

                    <p:commandButton
                            value="#{msg['button.cancel']}"
                            ajax="true"
                            actionListener="#{attributeController.cancelAddAttribute}"
                            update=":addeditform"
                            styleClass="ui-priority-primary"/>
                </p:panelGrid>
            </h:form>

        </p:dialog>
    </ui:define>
</ui:composition>

datamatrix-web/src/main/webapp/index.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:head>
    <title>#{msg['template.title']}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
</h:head>
<h:body>
    <h:outputText value="Current Version is 0.1" />
</h:body>
</html>

datamatrix-web/src/main/webapp/login.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:head>
    <title>Login Page</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
</h:head>

<h:body>

    <form jsf:id="form">
        <p>
            <strong>Username</strong>
            <input jsf:id="username" type="text" jsf:value="#{loginBean.username}" />
        </p>
        <p>
            <strong>Password</strong>
            <input jsf:id="password" type="password" jsf:value="#{loginBean.password}" />
        </p>
        <p>
            <input type="submit" value="Login" jsf:action="#{loginBean.login}" />
        </p>
    </form>

</h:body>

</html>

datamatrix-web/src/main/webapp/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:body>

    <p:menubar>
        <p:submenu
            label="#{msg['mainmenu.basedata']}">
            <p:menuitem value="#{msg['mainmenu.attributes']}" url="attributes.jsf" />
            <p:menuitem value="#{msg['mainmenu.types']}" url="types.jsf" />

        </p:submenu>
    </p:menubar>

</h:body>

</html>

datamatrix-web/src/main/webapp/template.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:head>
    <title>#{msg['template.title']}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
</h:head>
<h:body>
    <ui:include src="menu.xhtml" />
    <br />
    <ui:insert name="content"/>
</h:body>
</html>

datamatrix-web/src/main/webapp/types.xhtml
<ui:composition template="template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:define name="content">
        <h:form id="listform">

            <p:panelGrid>
                <p:row>
                    <p:column>
                        <p:treeTable
                                id="typestree"
                                value="#{typeController.rootNodes}"
                                var="type"
                                selectionMode="single"
                                selection="#{typeController.selectedTreeNode}">

                            <p:ajax
                                    event="select"
                                    listener="#{typeController.onSelectTypeNode}" />

                            <p:column
                                headerText="#{msg['datatable.type.number']}">
                                <h:outputText value="#{type.number}" />
                            </p:column>

                            <p:column
                                headerText="#{msg['datatable.type.name']}">
                                <h:outputText value="#{type.name}" />
                            </p:column>

                            <p:column
                                headerText="#{msg['datatable.type.description']}">
                                <h:outputText value="#{type.description}" />
                            </p:column>

                        </p:treeTable>
                    </p:column>

                    <p:column>
                        <p:dataTable
                                id="attributesTable"
                                var="attr"
                                value="#{typeController.getAttributesforType()}"
                                rowKey="#{attr.id}"
                                paginator="true"
                                rows="15"
                                paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                rowsPerPageTemplate="5,10,15"
                                paginatorPosition="bottom">

                            <p:column headerText="#{msg['datatable.attribute.id']}">
                                <h:outputText value="#{attr.id}"/>
                            </p:column>

                            <p:column headerText="#{msg['datatable.attribute.number']}">
                                <h:outputText value="#{attr.number}"/>
                            </p:column>

                            <p:column headerText="#{msg['datatable.attribute.name']}">
                                <h:outputText value="#{attr.name}"/>
                            </p:column>

                            <p:column headerText="#{msg['datatable.attribute.description']}">
                                <h:outputText value="#{attr.description}"/>
                            </p:column>

                        </p:dataTable>
                    </p:column>
                </p:row>

                <p:row>
                    <p:column colspan="2">
                        <p:commandButton
                                id="buttonaddtype"
                                value="#{msg['button.type.addtype']}"
                                ajax="true"
                                actionListener="#{typeController.addType}"
                                update=":addeditform"
                                styleClass="ui-priority-primary"/>

                        <p:commandButton
                                id="buttonedittype"
                                value="#{msg['button.type.edittype']}"
                                ajax="true"
                                actionListener="#{typeController.editType}"
                                update=":addeditform"
                                disabled="#{not typeController.isEditable()}"
                                styleClass="ui-priority-primary"/>

                        <p:commandButton
                                id="buttonaddattribute"
                                value="#{msg['button.type.addattribute']}"
                                ajax="true"
                                actionListener="#{typeController.openAddAttributeDialog}"
                                disabled="#{not typeController.isAttributeAddable()}"
                                styleClass="ui-priority-primary"/>

                        <p:commandButton
                                id="buttonarchivetype"
                                value="#{msg['button.type.archivetype']}"
                                ajax="true"
                                actionListener="#{typeController.archiveType}"
                                disabled="#{not typeController.isArchivable()}"
                                styleClass="ui-priority-primary"/>
                    </p:column>
                </p:row>

            </p:panelGrid>

        </h:form>

        <p:dialog
                id="addattributedialog"
                modal="true"
                resizable="false"
                draggable="false"
                closable="false"
                header="#{msg['type.addattribute.dialogtitle']}"
                widgetVar="addattributedialog">

            <h:form id="selectattributesform">

                <p:panelGrid>

                    <p:row>
                        <p:column colspan="2">

                            <p:dataTable
                                    value="#{typeController.availableAttributes()}"
                                    var="attr"
                                    id="attributesTable"
                                    rowKey="#{attr.id}"
                                    paginator="true"
                                    rows="15"
                                    paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                    rowsPerPageTemplate="5,10,15"
                                    selection="#{typeController.selectedAttributesToAdd}"
                                    paginatorPosition="bottom">

                                <p:column
                                        selectionMode="multiple"/>

                                <p:column headerText="#{msg['datatable.attribute.number']}">
                                    <h:outputText value="#{attr.number}"/>
                                </p:column>

                                <p:column headerText="#{msg['datatable.attribute.name']}">
                                    <h:outputText value="#{attr.name}"/>
                                </p:column>

                            </p:dataTable>


                        </p:column>
                    </p:row>

                    <p:row>
                        <p:column>
                            <p:commandButton
                                    value="#{msg['button.save']}"
                                    ajax="true"
                                    actionListener="#{typeController.saveAttributes}"
                                    styleClass="ui-priority-primary"/>
                        </p:column>

                        <p:column>
                            <p:commandButton
                                    value="#{msg['button.cancel']}"
                                    ajax="true"
                                    actionListener="#{typeController.cancelAddAttributes}"
                                    styleClass="ui-priority-primary"/>
                        </p:column>
                    </p:row>

                </p:panelGrid>

            </h:form>

        </p:dialog>

        <p:dialog
                id="addeditdialog"
                modal="true"
                resizable="false"
                draggable="false"
                closable="false"
                header="#{msg['type.addedit.dialogtitle']}"
                widgetVar="addeditdialog">

            <h:form id="addeditform">
                <p:panelGrid columns="2">

                    <h:outputText value="#{msg['type.form.parent']}" />
                    <h:inputText readonly="true" value="#{typeController.type.parent ne null ? typeController.type.parent.name : ''}" />

                    <h:outputText value="#{msg['type.form.number']}"/>
                    <h:inputText value="#{typeController.type.number}"/>

                    <h:outputText value="#{msg['type.form.name']}"/>
                    <h:inputText value="#{typeController.type.name}"/>

                    <h:outputText value="#{msg['type.form.description']}"/>
                    <h:inputText value="#{typeController.type.description}"/>

                    <p:commandButton
                            value="#{msg['button.save']}"
                            ajax="true"
                            actionListener="#{typeController.saveType}"
                            update=":addeditform"
                            styleClass="ui-priority-primary"/>

                    <p:commandButton
                            value="#{msg['button.cancel']}"
                            ajax="true"
                            actionListener="#{typeController.cancelAddType}"
                            update=":addeditform"
                            styleClass="ui-priority-primary"/>
                </p:panelGrid>
            </h:form>

        </p:dialog>
    </ui:define>
</ui:composition>